---

env:
  node: true
  es2020: true

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-alert: 0
  no-undef: 0
  no-console: 0
  import/extensions: 0
  import/no-named-as-default-member: 0